baseURL = "https://chealthdemo/"
languageCode = "en-us"
title = "Welcome"
theme = "chdemo"
description = "Caroline Health demo page"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "carolinehealth"
  github = ""
  twitter = ""
  email = ""

[[menu.main]]
    name = "All Benefits"
    weight = -102
    url = "/benefits/all/"
[[menu.main]]
    name = "PDF"
    weight = -101
    url = "http://www.raymondjames.com/about/openenrollment/2018_benefits%20guide_1.9.17.pdf"
[[menu.main]]
    name = "About"
    weight = -100
    url = "/about/"
